
version: "3.7"
services:
  # mqtt5 eclipse-mosquitto
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./mqtt-broker/config:/mosquitto/config:rw
      - ./mqtt-broker/data:/mosquitto/data:rw
      - ./mqtt-broker/log:/mosquitto/log:rw
    restart: unless-stopped

  ws-server:
    build: ws-server
    ports:
      - "8765:8765"
    environment:
      - PYTHONUNBUFFERED=1

# volumes for mapping data,config and log
volumes:
  config:
  data:
  log:

networks:
  default:
    name: mqtt-network
  
  websocket-network:
    driver: bridge
